[versions]
version-code = "1"
version-name = "1.0.0"
app-pkg = "com.albumsgenerator.app"
app-name = "Albums Generator"
app-vendor = "1001albumsgenerator"
app-description = "Explore the history of music. One album a day. From the book 1001 Albums You Must Hear Before You Die."
app-menugroup = "Other"
activity-compose = "1.12.2"
android-compileSdk = "36"
android-gradle = "9.1.0-alpha05"
android-minSdk = "28"
android-targetSdk = "36"
coil = "3.3.0"
compose = "1.11.0-alpha01"
datastore = "1.2.0"
ktor = "3.3.3"
kotlin = "2.3.0"
kotlinter = "5.3.0"
kotlinx-coroutines = "1.10.2"
ksp = "2.3.4"
lifecycle = "2.10.0-alpha07"
metro = "0.9.4"
navigation3 = "1.1.0-alpha01"
room = "2.8.4"

[libraries]
compose-webview-multiplatform = "com.saralapps:composemultiplatformwebview:0.1.5"
jetpack-compose-rules = "io.nlopez.compose.rules:ktlint:0.5.3"
material3-placeholder = "com.eygraber:compose-placeholder-material3:1.0.12"
touchlab-kermit = "co.touchlab:kermit:2.0.8"

# AndroidX
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-sqlite-bundled = "androidx.sqlite:sqlite-bundled:2.6.2"

# JetBrains
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = "org.jetbrains.compose.material3:material3:1.10.0-alpha05"
compose-nav3 = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "navigation3" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose" }
jetbrains-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
jetbrains-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
jetbrains-lifecycle-viewmodel-navigation3 = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycle" }
jetbrains-material-icons-extended = "org.jetbrains.compose.material:material-icons-extended:1.7.3"

# Coil
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil"}
coil-network = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil"}

# KotlinX
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.7.1"
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0"

# Ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Metro
metrox-viewmodel-compose = { module = "dev.zacsweers.metro:metrox-viewmodel-compose", version.ref = "metro" }

# Room
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "android-gradle" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
gradle-buildconfig-plugin = "com.github.gmazzo.buildconfig:6.0.7"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
metro = { id = "dev.zacsweers.metro", version.ref = "metro" }
room = { id = "androidx.room", version.ref = "room" }